language: objective-c
osx_image: xcode8.2
xcode_project: iOSSwiftStarterPack.xcworkspace
xcode_scheme: iOSSwiftStarterPack
xcode_sdk: iphonesimulator10.0
script:
    - xcodebuild -scheme iOSSwiftStarterPack CODE_SIGNING_REQUIRED=NO -workspace iOSSwiftStarterPack.xcworkspace -sdk iphonesimulator build test
