disabled_rules: # rule identifiers to exclude from running, see all rules here: https://github.com/realm/SwiftLint
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - todo
  - type_body_length
  - variable_name
  - type_name
  - function_parameter_count

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
